server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: administration
  liquibase:
    enabled: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - info
          - health
          - metrics